-- Generated by Oracle SQL Developer REST Data Services 20.2.0.175.1842
-- Exported REST Definitions from ORDS Schema Version 20.3.0.r3011819
-- Schema: ODI_DEMO   Date: Tue Feb 02 14:29:32 CET 2021
--
DECLARE
  l_roles     OWA.VC_ARR;
  l_modules   OWA.VC_ARR;
  l_patterns  OWA.VC_ARR;
BEGIN
  ORDS.ENABLE_SCHEMA(
      p_enabled             => TRUE,
      p_schema              => 'ODI_DEMO',
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => 'odidemo',
      p_auto_rest_auth      => FALSE);    

  ORDS.DEFINE_MODULE(
      p_module_name    => 'demo',
      p_base_path      => '/demo/',
      p_items_per_page =>  25,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'demo',
      p_pattern        => 'cust360/:custid',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'demo',
      p_pattern        => 'cust360/:custid',
      p_method         => 'GET',
      p_source_type    => 'resource/lob',
      p_items_per_page =>  25,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'select ''application/json'', 
 json_object (
   ''lastName'' is last_name,
   ''firstName'' is first_name,
   ''address'' is address,
   ''city'' is city,
   ''phone'' is phone,
   ''salesPerson'' is sp_first_name||'' ''||sp_last_name
 )  from v_cust360
 where custid = :custid'
      );
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'demo',
      p_pattern        => 'order360/:custid',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'demo',
      p_pattern        => 'order360/:custid',
      p_method         => 'GET',
      p_source_type    => 'resource/lob',
      p_items_per_page =>  25,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'select ''application/json'', json_object (
             ''custId'' is custid,
             ''orderId'' is order_id,
             ''order_date'' is order_date,
             ''items'' is json_arrayagg (json_object (
                ''product'' is product,
                ''quantity'' is qty,
                ''amount'' is amount
                ) returning clob
             )

       returning clob) json_data from v_orders360
       where custid = :custid
       group by custid, order_id, order_date'
      );

  ORDS.CREATE_ROLE(p_role_name  => 'oracle.dbtools.role.autorest.ODI_DEMO');

  l_roles(1)   := 'oracle.dbtools.autorest.any.schema';
  l_roles(2)   := 'oracle.dbtools.role.autorest.ODI_DEMO';
  l_modules(1) := 'demo';

  ORDS.DEFINE_PRIVILEGE(
      p_privilege_name => 'oracle.dbtools.autorest.privilege.ODI_DEMO',
      p_roles          => l_roles,
      p_patterns       => l_patterns,
      p_modules        => l_modules,
      p_label          => '',
      p_description    => '',
      p_comments       => NULL);      


  COMMIT; 

END;