-- Generated by Oracle SQL Developer REST Data Services 18.4.0.376.1900
-- Exported REST Definitions from ORDS Schema Version 18.3.0.r2701456
-- Schema: SVI_PORTAL   Date: Wed Apr 17 14:13:26 CEST 2019
--
BEGIN
  ORDS.ENABLE_SCHEMA(
      p_enabled             => TRUE,
      p_schema              => 'SVI_PORTAL',
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => 'svi_portal',
      p_auto_rest_auth      => FALSE);    

  ORDS.DEFINE_MODULE(
      p_module_name    => 'SVIfachlich',
      p_base_path      => '/api/',
      p_items_per_page =>  25,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);      
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'SVIfachlich',
      p_pattern        => 'alledaten',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'SVIfachlich',
      p_pattern        => 'alledaten',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page =>  25,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'select  *   
from v_alles where "partnernummer"=:partnernummer'
      );
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'SVIfachlich',
      p_pattern        => 'alledaten_mv',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'SVIfachlich',
      p_pattern        => 'alledaten_mv',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page =>  25,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'select  *   
from v_alles_mv where "partnernummer"=:partnernummer'
      );
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'SVIfachlich',
      p_pattern        => 'ansijoin',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'SVIfachlich',
      p_pattern        => 'ansijoin',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page =>  25,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'select  *   
from svi_stage.v_ansijoin where spark_partnernummer = :partnernummer'
      );
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'SVIfachlich',
      p_pattern        => 'ansijoinsuche',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'SVIfachlich',
      p_pattern        => 'ansijoinsuche',
      p_method         => 'GET',
      p_source_type    => 'json/query',
      p_items_per_page =>  25,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'select /* +first_rows */ 
*
from svi_stage.v_ansijoin'
      );
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'SVIfachlich',
      p_pattern        => 'ansioperations',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'SVIfachlich',
      p_pattern        => 'ansioperations',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page =>  25,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'select  * from svi_dip.v_ansioperations'
      );
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'SVIfachlich',
      p_pattern        => 'partner/:partnernummer/basisdaten_ori',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'SVIfachlich',
      p_pattern        => 'partner/:partnernummer/basisdaten_ori',
      p_method         => 'GET',
      p_source_type    => 'resource/lob',
      p_items_per_page =>  25,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'select  ''application/json'',
   json_object ( 
      ''executingUser'' value :current_user,
      ''result'' value 

        json_object(
               ''partnernummer'' value v."partnernummer",
               ''name'' value v."name",
               ''vorname'' value v."vorname",
               ''anrede'' value v."anrede",
               ''geburtsdatum'' value v."geburtsdatum",
               ''name2'' value v."name2",
               ''adressen'' value json_array (
                  json_object (
                  ''adresseZusatz'' value '''',
                  ''emaDatum'' value '''',
                  ''emaStatus'' value '''',
                  ''gueltigAb'' value '''',
                  ''gueltigBis'' value '''',
                  ''hauptadresse'' value ''true'' format json,
                  ''hausNr'' value '''',
                  ''landLangText'' value v."landLangText",
                  ''ort'' value v."ort",
                  ''ortsTeil'' value '''',
                  ''plz'' value v."plz",
                  ''postfach'' value '''',
                  ''strasse'' value v."strasse",
                  ''strasseHausNr'' value ''''
                  )
               ),
               ''kontaktdaten'' value json_object (
                  ''telefonNrPrivat'' value json_object (''nummer'' value v."telefonNrPrivatNummer"),
                  ''telefonNrMobilnummer'' value json_object (''nummer'' value v."telefonNrMobilnummer"),
                  ''emailPrivat'' value json_object (''adresse'' value v."emailPrivatadresse")
               )

      returning varchar2(32000) ),
      ''success'' value ''true''
   ) 
   from svi_portal.v_basisdaten v
where
-- suche nach Partnernummer
v."partnernummer" = :partnernummer
-- check auf VIP zugriff
AND v."vip" <= (select lvl from portal_acl where :current_user = portal_acl.username)
-- sortierung für reproduzierbare pagination'
      );
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'SVIfachlich',
      p_pattern        => 'partner/basisdaten',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'SVIfachlich',
      p_pattern        => 'partner/basisdaten',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page =>  25,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'select   * from
svi_portal.v_basisdaten v
where
-- suche nach Partnernummer
v."partnernummer" = :partnernummer'
      );
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'SVIfachlich',
      p_pattern        => 'partner_ori',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'SVIfachlich',
      p_pattern        => 'partner_ori',
      p_method         => 'GET',
      p_source_type    => 'resource/lob',
      p_items_per_page =>  25,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'select  ''application/json'',
   json_object ( 
      ''executingUser'' value :current_user,
      ''result'' value
      json_arrayagg (
         json_object(
               ''anrede'' value v."anrede",
               ''geburtsdatum'' value v."geburtsdatum",
               ''name'' value v."name",
               ''name2'' value v."name2",
               ''ort'' value v."ort",
               ''partnernr'' value v."partnernummer",
               ''plz'' value v."plz",
               ''strasseHausNr'' value v."strasse",
               ''trefferquote'' value 100,
               ''vorname'' value v."vorname"
        ) 
      returning varchar2(32000) ),
      ''success'' value ''true'' format json
    returning varchar2(32000) )
            from svi_portal.v_basisdaten v
where 
-- Suchfelder
v."name" = nvl (:name, v."name")
AND v."vorname" = nvl (:vorname, v."vorname")
AND to_char(v."geburtsdatum") = nvl (:geburtsdatum, to_char(v."geburtsdatum"))
AND v."strasse" = nvl (:strasse, v."strasse")
AND to_char(v."plz") = nvl (:plz, to_char(v."plz"))
AND v."ort" = nvl (:ort, v."ort")
-- maxCount, max Anzahl Ergebnisse
AND rownum <= nvl (:maxCount, 25)
-- Prüfung nach VIP Partner bzw. Benutzerberechtigung
AND v."vip" <= (select lvl from portal_acl where :current_user = portal_acl.username)'
      );
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'SVIfachlich',
      p_pattern        => 'schaeden',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'SVIfachlich',
      p_pattern        => 'schaeden',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page =>  25,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'select  * from
svi_portal.v_schaeden v
where
-- suche nach Partnernummer
v."partnernummer" = :partnernummer'
      );
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'SVIfachlich',
      p_pattern        => 'schaeden_ori',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'SVIfachlich',
      p_pattern        => 'schaeden_ori',
      p_method         => 'GET',
      p_source_type    => 'resource/lob',
      p_items_per_page =>  25,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'select  ''application/json'',
   json_object ( 
      ''executingUser'' value :current_user,
      ''result'' value json_object (
            ''schadenListe'' value JSON_ARRAYAGG (
               json_object (
                  ''bearbeitungStatus'' value v."bearbeitungStatus",
                  ''referat'' value '''',
                  ''risikobereich'' value '''',
                  ''risikobereichBezeichnung'' value v."risikobereichBezeichnung",
                  ''schadenIdentNummer'' value v."schadenIdentNummer",
                  ''schadenart'' value '''',
                  ''schadendatum'' value v."schadendatum",
                  ''spartenCode'' value '''',
                  ''summeReserven'' value '''',
                  ''summeZahlungen'' value '''',
                  ''tarifCode'' value '''',
                  ''tarifschadenindex'' value '''',
                  ''tarifschadenindexBezeichnung'' value '''',
                  ''vertragsnummer'' value ''''

               ) 
             returning varchar2(32000) ) --,
             --''weiterDatenVorhanden'' value ''false'' format json
      returning varchar2(32000) ),
      ''success'' value ''true''
      returning varchar2(32000)
   ) 
from svi_portal.v_schaeden v
where v."partnernummer" = :partnernummer
and rownum between nvl(:pagination_offset, 0) and 250+nvl(:pagination_offset, 0)
AND v."vip" <= (select lvl from portal_acl where :current_user = portal_acl.username)
order by v."schadendatum"'
      );
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'SVIfachlich',
      p_pattern        => 'vertraege/kfz',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'SVIfachlich',
      p_pattern        => 'vertraege/kfz',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page =>  25,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'select  * from
svi_portal.v_kfz v
where
-- suche nach Partnernummer
v."partnernummer" = :partnernummer'
      );
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'SVIfachlich',
      p_pattern        => 'vertraege/kfz_ori',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'SVIfachlich',
      p_pattern        => 'vertraege/kfz_ori',
      p_method         => 'GET',
      p_source_type    => 'resource/lob',
      p_items_per_page =>  25,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'select  ''application/json'',
    json_object ( 
      ''executingUser'' value :current_user,
      ''result'' value JSON_ARRAYAGG (
            json_object(
               ''partnernummer'' value v."partnernummer",
               ''istAktiv'' value ''true'' format json,
               ''produktLangName'' value v."produktLangname",
               ''produktKurzName'' value '''',
               ''vertragStatus'' value '''',
               ''vertragsEnde'' value '''',
               ''vertragsNr'' value v."vertragsNr",
               ''vertragsVersion'' value '''',
               ''vertragsbeginn'' value '''',
               ''vertragsobjekte'' value json_arrayagg (
                  json_object (
                     ''jahresBruttoBeitrag'' value '''',
                     ''jahresNettoBeitrag'' value '''',
                     ''objektArt'' value v."objektArt",
                     ''objektBezeichnung'' value v."objektBezeichnung",
                     ''objektartLangname'' value '''',
                     ''objektnummer'' value v."objektnummer",
                     ''objektpartnerVorhanden'' value '''',
                     ''objektversion'' value '''',
                     ''vertragsobjektType'' value ''''
                  )
               ) returning varchar2(32000)
            ) 
      returning varchar2(32000) ),
      ''success'' value ''true''
      returning varchar2(32000)
   ) 

from svi_portal.v_kfz v
where v."partnernummer" = :partnernummer
and rownum between nvl(:pagination_offset, 1) and 250+nvl(:pagination_offset, 0)
AND v."vip" <= (select lvl from portal_acl where :current_user = portal_acl.username)
group by  v."objektArt", v."objektBezeichnung", v."objektnummer",v."vertragsNr", v."partnernummer", v."produktLangname"'
      );
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'SVIfachlich',
      p_pattern        => 'vertraege/komposit',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'SVIfachlich',
      p_pattern        => 'vertraege/komposit',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page =>  25,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'select  * from
svi_portal.v_komposit v
where
-- suche nach Partnernummer
v."partnernummer" = :partnernummer'
      );
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'SVIfachlich',
      p_pattern        => 'vertraege/komposit_ori',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'SVIfachlich',
      p_pattern        => 'vertraege/komposit_ori',
      p_method         => 'GET',
      p_source_type    => 'resource/lob',
      p_items_per_page =>  25,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'select  ''application/json'',
   json_object ( 
      ''executingUser'' value :current_user,
      ''result'' value JSON_ARRAYAGG (
            json_object(
               ''partnernummer'' value v."partnernummer",
               ''istAktiv'' value ''true'' format json,
               ''produktLangName'' value v."produktLangname",
               ''produktKurzName'' value '''',
               ''vertragStatus'' value '''',
               ''vertragsEnde'' value '''',
               ''vertragsNr'' value v."vertragsNr",
               ''vertragsVersion'' value '''',
               ''vertragsbeginn'' value '''',
               ''vertragsobjekte'' value json_arrayagg (
                  json_object (
                     ''jahresBruttoBeitrag'' value '''',
                     ''jahresNettoBeitrag'' value '''',
                     ''objektArt'' value v."objektArt",
                     ''objektBezeichnung'' value v."objektBezeichnung",
                     ''objektartLangname'' value '''',
                     ''objektnummer'' value v."objektnummer",
                     ''objektpartnerVorhanden'' value '''',
                     ''objektversion'' value '''',
                     ''vertragsobjektType'' value ''''
                  )
               ) returning varchar2(32000)

            ) 
      returning varchar2(32000) ),
      ''success'' value ''true''
      returning varchar2(32000)
   ) 

from svi_portal.v_komposit v
where v."partnernummer" = :partnernummer
and rownum between nvl(:pagination_offset, 0) and 250+nvl(:pagination_offset, 0)
AND v."vip" <= (select lvl from portal_acl where :current_user = portal_acl.username)
group by v."partnernummer", v."produktLangname",   v."vertragsNr", v."objektArt", v."objektBezeichnung", v."objektnummer"'
      );
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'SVIfachlich',
      p_pattern        => 'vertraege/kranken',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'SVIfachlich',
      p_pattern        => 'vertraege/kranken',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page =>  25,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'select  * from
svi_portal.v_kranken v
where
-- suche nach Partnernummer
v."partnernummer" = :partnernummer'
      );
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'SVIfachlich',
      p_pattern        => 'vertraege/kranken_ori',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'SVIfachlich',
      p_pattern        => 'vertraege/kranken_ori',
      p_method         => 'GET',
      p_source_type    => 'resource/lob',
      p_items_per_page =>  25,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'select  ''application/json'',
   json_object ( 
      ''executingUser'' value :current_user,
      ''result'' value JSON_ARRAYAGG (
            json_object(
               ''partnernummer'' value v."partnernummer",
               ''istAktiv'' value ''true'' format json,
               ''produktLangName'' value v."produktLangname",
               ''produktKurzName'' value '''',
               ''vertragStatus'' value '''',
               ''vertragsEnde'' value '''',
               ''vertragsNr'' value v."vertragsNr",
               ''vertragsVersion'' value '''',
               ''vertragsbeginn'' value '''',
               ''vertragsobjekte'' value json_arrayagg (
                  json_object (
                     ''jahresBruttoBeitrag'' value '''',
                     ''jahresNettoBeitrag'' value '''',
                     ''objektArt'' value '''',
                     ''objektBezeichnung'' value '''',
                     ''objektartLangname'' value '''',
                     ''objektnummer'' value v."objektnummer",
                     ''objektpartnerVorhanden'' value '''',
                     ''objektversion'' value '''',
                     ''vertragsobjektType'' value ''''
                  )
               ) returning varchar2(32000)
            ) 
      returning varchar2(32000) ),
      ''success'' value ''true''
   ) 

from svi_portal.v_kranken v
where v."partnernummer" = :partnernummer
and rownum between nvl(:pagination_offset, 0) and 250+nvl(:pagination_offset, 0)
AND v."vip" <= (select lvl from portal_acl where :current_user = portal_acl.username)
group by v."partnernummer", v."produktLangname",   v."vertragsNr", v."objektnummer"'
      );
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'SVIfachlich',
      p_pattern        => 'vertraege/leben',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'SVIfachlich',
      p_pattern        => 'vertraege/leben',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page =>  25,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'select  * from
svi_portal.v_leben v
where
-- suche nach Partnernummer
v."partnernummer" = :partnernummer'
      );
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'SVIfachlich',
      p_pattern        => 'vertraege/leben_ori',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'SVIfachlich',
      p_pattern        => 'vertraege/leben_ori',
      p_method         => 'GET',
      p_source_type    => 'resource/lob',
      p_items_per_page =>  25,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'select  ''application/json'',
   json_object ( 
      ''executingUser'' value :current_user,
      ''result'' value json_object(
            ''vertragSucheStubList'' value json_arrayagg(
               json_object (
                  ''istAktiv'' value ''true'' format json,
                  ''produktLangname'' value v."produktLangname",
                  ''produktkurzname'' value '''',
                  ''vertragStatus'' value '''',
                  ''vertragsEnde'' value '''',
                  ''vertragsNr'' value v."vertragsNr",
                  ''vertragsVersion'' value '''',
                  ''vertragsbeginn'' value '''',
                  ''vertragsobjekte'' value json_arrayagg (
                  json_object (
                     ''jahresBruttoBeitrag'' value '''',
                     ''jahresNettoBeitrag'' value '''',
                     ''objektArt'' value '''',
                     ''objektBezeichnung'' value '''',
                     ''objektartLangname'' value '''',
                     ''objektnummer'' value v."objektnummer",
                     ''objektpartnerVorhanden'' value '''',
                     ''objektversion'' value '''',
                     ''vertragsobjektType'' value ''''
                  )
               ) returning varchar2(32000)
            )
        )--,
        --''weitereSaetzeVorhanden'' value ''false''  format json
        returning varchar2(32000) ),
      ''success'' value ''true''
   ) 

from svi_portal.v_leben v
where v."partnernummer" = :partnernummer
and rownum between nvl(:pagination_offset, 0) and 250+nvl(:pagination_offset, 0)
AND v."vip" <= (select lvl from portal_acl where :current_user = portal_acl.username)
group by v."partnernummer", v."produktLangname",   v."vertragsNr", v."objektnummer"'
      );
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'SVIfachlich',
      p_pattern        => 'vertraege/rechtschutz',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'SVIfachlich',
      p_pattern        => 'vertraege/rechtschutz',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page =>  25,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'select  * from
svi_portal.v_rechtsschutz v
where
-- suche nach Partnernummer
v."partnernummer" = :partnernummer'
      );
  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'SVIfachlich',
      p_pattern        => 'vertraege/rechtschutz_ori',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);
  ORDS.DEFINE_HANDLER(
      p_module_name    => 'SVIfachlich',
      p_pattern        => 'vertraege/rechtschutz_ori',
      p_method         => 'GET',
      p_source_type    => 'resource/lob',
      p_items_per_page =>  25,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'select  ''application/json'',
   json_object ( 
      ''executingUser'' value :current_user,
      ''result'' value JSON_ARRAYAGG (
            json_object(
               ''partnernummer'' value v."partnernummer",
               ''istAktiv'' value ''true'' format json,
               ''produktLangName'' value v."produktLangname",
               ''produktKurzName'' value '''',
               ''vertragStatus'' value '''',
               ''vertragsEnde'' value '''',
               ''vertragsNr'' value v."vertragsNr",
               ''vertragsVersion'' value '''',
               ''vertragsbeginn'' value '''',
               ''vertragsobjekte'' value json_arrayagg (
                  json_object (
                     ''jahresBruttoBeitrag'' value '''',
                     ''jahresNettoBeitrag'' value '''',
                     ''objektArt'' value '''',
                     ''objektBezeichnung'' value '''',
                     ''objektartLangname'' value '''',
                     ''objektnummer'' value v."objektnummer",
                     ''objektpartnerVorhanden'' value '''',
                     ''objektversion'' value '''',
                     ''vertragsobjektType'' value ''''
                  )
               ) returning varchar2(32000)
            ) 
      returning varchar2(32000) ),
      ''success'' value ''true''
   ) 

from svi_portal.v_rechtsschutz v
where v."partnernummer" = :partnernummer
and rownum between nvl(:pagination_offset, 0) and 250+nvl(:pagination_offset, 0)
group by v."partnernummer", v."produktLangname",   v."vertragsNr",  v."objektnummer"'
      );


  COMMIT; 
END;